apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: ccenv
  namespace: default
spec:
  ports:
  - name: "none"
    nodePort: 0
    port: 3000
    protocol: ""
    targetPort: 0
  selector:
    service: ccenv
status:
  loadBalancer: {}