apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: cli
  namespace: default
spec:
  ports:
  - name: "none"
    nodePort: 0
    port: 7051
    protocol: ""
    targetPort: 0
  selector:
    service: cli
status:
  loadBalancer: {}