apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: cli
  name: cli
  namespace: default
spec:
  replicas: 1
  selector:
    service: cli
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cli
    spec:
      containers:
      - command:
        - sh
        args: ["-c", "ln -s /root/.fabric-ca/$$CERT_ID /etc/hyperledger/fabric/msp/sampleconfig; sleep 120; ./channel_test.sh; sleep 10000"]
        env:
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: 'true'
        - name: CORE_PEER_ADDRESS
          value: peer0:7051
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_NEXT
          value: 'true'
        - name: CORE_PEER_ENDORSER_ENABLED
          value: 'true'
        - name: CERT_ID
          value: peer3
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_COMMITTER_LEDGER_ORDERER
          value: orderer:7050
        - name: GOPATH
          value: '/opt/gopath'
        image: gcr.io/netvote-160820/netvote/fabric-peer
        imagePullPolicy: ""
        name: cli
        workingDir: /root
        ports:
        - containerPort: 7051
        - containerPort: 7053
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status:
  replicas: 0