apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    service: ca
  name: ca
  namespace: default
spec:
  replicas: 1
  selector:
    service: ca
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: ca
    spec:
      containers:
      - command:
        - sh
        args: ["-c", "sleep 10; fabric-ca server start -ca /.fabric-ca/$$CA_CERTIFICATE -ca-key /.fabric-ca/$$CA_KEY_CERTIFICATE -config /etc/hyperledger/fabric-ca/server-config.json -address '0.0.0.0'"]
        env:
        - name: CA_CERTIFICATE
          value: peerOrg0_cert.pem
        - name: CA_KEY_CERTIFICATE
          value: peerOrg0_pk.pem
        image: sfhackfest22017/fabric-ca:x86_64-0.7.0-snapshot-6294c57
        imagePullPolicy: ""
        name: ca
        ports:
        - containerPort: 7054
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status:
  replicas: 0