apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: netvote-api
    service: netvote-api
  name: netvote-api
  namespace: default
spec:
  replicas: 3
  selector:
    service: netvote-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: netvote-api
    spec:
      containers:
      - image: gcr.io/netvote-160820/netvote/api:latest
        env:
        - name: ORDERER_GRPC_URL
          value: grpc://orderer:7050
        - name: PEER_GRPC_URLS
          value: grpc://peer0:7051,grpc://peer1:7051,grpc://peer2:7051
        - name: EVENT_HUB_URL
          value: grpc://peer0:7053
        name: netvote-api
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status:
  replicas: 0
