apiVersion: v1
kind: Service
metadata:
  name: netvote-deployer
  namespace: default
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 3000
    protocol: ""
    targetPort: 0
  selector:
    service: netvote-deployer
status:
  loadBalancer: {}