apiVersion: v1
kind: Service
metadata:
  name: netvote-api
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    service: netvote-api
  type: "LoadBalancer"
  loadBalancerIP: 104.198.240.210