apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: orderer
  namespace: default
spec:
  ports:
  - name: ""
    nodePort: 0
    port: 7050
    protocol: ""
    targetPort: 0
  selector:
    service: orderer
status:
  loadBalancer: {}