apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: peer1
  namespace: default
spec:
  ports:
  - name: "transaction"
    nodePort: 0
    port: 7051
    protocol: ""
    targetPort: 0
  selector:
    service: peer1
status:
  loadBalancer: {}