apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: peer0
  namespace: default
spec:
  ports:
  - name: "transaction"
    nodePort: 0
    port: 7051
    protocol: ""
    targetPort: 0
  - name: "events"
    nodePort: 0
    port: 7053
    protocol: ""
    targetPort: 0
  selector:
    service: peer0
status:
  loadBalancer: {}